version: '3.7'
services:

  tor-node:
    build: ./tor-privoxy
    restart: always
    ports:
    - "9051:9051" # Tor control port
    - "8118:8118" # Privoxy
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=scrapy-out
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nopassword
    volumes:
      - ./mongodb/mongo-volume:/data/db
    ports:
      - 27017:27017